### ISSUE TITLE
Clarification: particle state convention

### ISSUE THREAD

**Issue by roman-martin** [SixTrack/pysixtrack#46]
In  the ```__init__```  of Particles [a comment](https://github.com/SixTrack/pysixtrack/blob/27d9fe585a2cb0b5da959e7d9b47b460dd7723bb/pysixtrack/particles.py#L227) indicates that `particle.state == 1` means the particle is lost. However, in the [Limit](https://github.com/SixTrack/pysixtrack/blob/27d9fe585a2cb0b5da959e7d9b47b460dd7723bb/pysixtrack/elements.py#L311) classes it appears that `particle.state == 1` is the only state that is **not** lost.

**Comment by martinschwinzerl** [comment]
Sorry for the late reply, please ignore the comment in the original file, the behavior of the Limit elements is the correct one. Please cf. PR #48 for an attempt to clarify this confusion
